### ISSUE TITLE
Compilation time estimation doesn't seem to work as intended in 20-title.sh

### ISSUE THREAD

**Issue by guitoo** [vaeth/portage-bashrc-mv#18]
The displayed compilation is the first compilation time.

qlop now shows both unmerge and merge history. Option -m shows only merges.
$sec is set using the first merge. Any reasons you don't use qlop -aCMm to get an average?

Or you could use something like this, to get average over the last 5 merges.
qlop -tCMm chromium | tail -n 5 | awk '{ total += $4; count++ } END { if (count!= 0) print int(total/count) }'

**Comment by vaeth** [comment]
I expected to get the last compilation time: IMHO, this is more realistic, since compilation time can change rather drastic with major package releases.
The idea to manually calculate the average time for the last X emerges covers both, since for X=1 one gets the behavior which I prefer, but users can customize it differently. Using tail in the pipeline seems wrong if awk follows, so I wrote more complex awk code which avoids it.
The missing -m was a clear mistake, of course.

Should be fixed in v8.1
