### ISSUE TITLE
filter PYTHON_FLAGS

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/portage-bashrc-mv#5]
I found that some packages uses the following flags:
PYTHON_CFLAGS
PYTHON_CXXFLAGS
PYTHON_CPPFLAGS
PYTHON_LDFLAGS

causing various problems (they remember flags which I didn't set explicitly ...)
These variables can be stripped too?

**Comment by vaeth** [comment]
These variables are set/used by the python eclasses, not necessarily in the setup phase where portage-bashrc-mv typically sets the *FLAGS variables.
If these variables need to be hacked, this must happen in a way particular to each ebuild: There is no "generic" way to hack this, and therefore, I think that such a hack is not appropriate for bashrc.

Actually, the proper way would be if the .pc file generated by the corresponding python implementation would contain only the actually needed *FLAGS and if that .pc file is used only to add (not to replace) the corresponding *FLAGS to those from the "usual" variables. I haven't checked whether this is the case or can be fixed easily. But this (i.e. the gentoo eclass, python upstream, or the particular python package upstream, depending on where things go wrong) is where the issue actually should be reported. Working around the issue with specific hacks should be the very last resort (and can only be a temporary hack anyway, not the correct fix).

**Comment by Alessandro-Barbieri** [comment]
I don't have a patch, I only modified on the fly the file when emerging but with unsuccess. It seems that if you set (have to figure if empty variable breaks things) the PYTHON_*FLAGS portage is not happy.

**Comment by Alessandro-Barbieri** [comment]
To summarize: python (ruby too ...) remember the flags used to compile it and put them in a file, this file is called by an eclass that set the variables which in turn are used by some python packages. I'm right?
Not very gentoo-ish imho.

I found this (ruby):
https://bugs.gentoo.org/show_bug.cgi?id=476668
https://bugs.gentoo.org/show_bug.cgi?id=443780
https://bugs.gentoo.org/show_bug.cgi?id=316095

**Comment by vaeth** [comment]
> It seems that if you set (have to figure if empty variable breaks things) the PYTHON_*FLAGS portage is not happy

Yes: They are set by some function calls within the eclass, and in turn are used by other function calls within that eclass. This might even happen during the same phase. That's why I meant that one has to patch such ebuilds individually, and there is not a "generic" scheme for doing such patches.

> python (ruby too ...) remember the flags used to compile it and put them in a file

Yes, in a .pc file which is read by pkg-config. This is one of the standard ways to add e.g. necessary -l… or -L… -I… flags for libraries or library paths/include paths. If python stores there "standard" flags, this seems wrong, though perhaps it is meant to deal with things like -flto properly. Anyway, this must be discussed with python upstream.

> this file is called by an eclass

pkg-config is called by the eclass. This might be reasonable if the corresponding python package has no build system on its own which does this.

**Comment by vaeth** [comment]
I think in the moment there is nothing which could be fixed in portage-bashrc-mv. Therefore, closing.
